project:
  type: website
  output-dir: docs

exeucte:
  eval: false

website:
  title: "Kevin's Homepage"
  image: quarto.png
  google-analytics: G-S9W9LVHXJK
  page-footer:
    center:
      - icon: linkedin
        href: https://www.linkedin.com/in/kevin-maik-jablonka/
      - icon: twitter
        href: https://twitter.com/kmjablonka
      - icon: github
        href: https://github.com/kjappelbaum
      - icon: envelope
        href: https://mailhide.io/e/o4LeOUlq
      - icon: bi-mortarboard-fill
        href: https://scholar.google.com/citations?user=R2ntI8IAAAAJ&hl=en
  favicon: favicon.ico
  open-graph: true
  twitter-card:
    creator: "@kmjablonka"
  site-url: "https://kjablonka.com/"
  description: "Kevin Maik Jablonka's homepage."
  repo-url: https://github.com/kjappelbaum/kjappelbaum.github.io
  repo-actions: [edit]
  repo-branch: master
  navbar:
    title: false
    background: dark
    pinned: false
    collapse: false
    left:
      # # ğŸ  ğŸ“® ğŸ‘¨ğŸ½â€ğŸ’» ğŸ ğŸ¤ ğŸ“š
      - icon: home
        text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      # - text: "CV"
      #   href: cv.qmd
      - text: Research
        href: research.qmd
      - text: Open Source
        file: opensource/opensource.qmd
      - text: Teaching
        href: teaching.qmd
format:
  html:
    theme: [solar, custom.scss]
    css:
      - styles.css
    toc: true
    comments:
      utterances:
        repo: kjappelbaum/kjappelbaum.github.io
